version: "3"
services:
  db:
    image: postgres:14
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddit
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 5051:8080
