declare const classNames: {
  readonly form__inner: "form__inner"
  readonly form__label: "form__label"
  readonly form__info: "form__info"
  readonly form__input: "form__input"
  readonly form__prefix: "form__prefix"
  readonly form__characters: "form__characters"
  readonly form__error: "form__error"
  readonly form__footer: "form__footer"
  readonly wrapper: "wrapper"
  readonly btn: "btn"
  readonly "btn--primary": "btn--primary"
  readonly "btn--secondary": "btn--secondary"
}
export default classNames
export type ClassNames =
  | "form__inner"
  | "form__label"
  | "form__info"
  | "form__input"
  | "form__prefix"
  | "form__characters"
  | "form__error"
  | "form__footer"
  | "wrapper"
  | "btn"
  | "btn--primary"
  | "btn--secondary"
